### PR TITLE
Update kraken.py

### PR DESCRIPTION
**Pull request by angeloruggieridj**
Fixed failed download from KrakenFile website

### CODE REVIEW

**Comment by angeloruggieridj** [comment]
Fixed failed download from KrakenFile website

**Comment by tha23rd** [comment]
Hi, thanks for the contribution!

This repo has some dust on it, will need a couple of days to re-orient.

**Comment by yami-no-ryuu** [comment]
What is going on? Any reason this is not merged?
Another bit is super(exception) failing in python 3.12.

**Comment by tha23rd** [comment]
Sorry for the delay. I've tested/merged this in.

Will need some time to publish a new release on pypi.

**Pull request merged**
